services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - "xpack.security.enabled=false"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    #networks:
    #  - elastic

  #kibana:
  #  image: docker.elastic.co/kibana/kibana:8.15.3
  #  container_name: kibana
  #  environment:
  #    - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #  ports:
  #    - 5601:5601
  #  networks:
  #    - elastic

#networks:
#  elastic:
#    driver: bridge
