version: '3'

services:
  postgres_latin1:
    build: .
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
