version: '3'

services:
  smtp4dev:
    image: rnwood/smtp4dev:v3.1
    container_name: smtp4dev
    ports:
      - '5000:80'
      - '125:25'
      - '1143:143'
    volumes:
        - ./smtp4dev-data:/smtp4dev
