services:
  oracle:
    image: gvenzl/oracle-xe:latest
    environment:
      ORACLE_PASSWORD: oracle
      APP_USER: oracle
      APP_USER_PASSWORD: oracle
    ports:
      - 11521:1521
    volumes:
      - ./oradata:/opt/oracle/oradata
